name: CI/CD for my-shop App

on:
  push:
    branches:
      - main   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

     
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

     
      - name: Install dependencies
        run: npm ci

      # Step 4: Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build Docker image and push to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myshop:latest

     
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myshop:latest
            docker stop myshop || true
            docker rm myshop || true
            docker run -d -p 3000:3000 --name myshop \
            -e MONGODB_URL="mongodb+srv://myshopuser:myshop123@cluster0.tn3hwnw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" \
            -e NEXTAUTH_URL="http://13.234.29.175:3000" \
            -e NEXTAUTH_SECRET="secretId" \
            meghana1724/myshop:latest

